spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo
    username: {insert}
    password: {insert}
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
  servlet:
    context-path: /demo3
